<Project Sdk="Godot.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">$(AndroidFrameworkVersion)</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <RootNamespace>Godot.MoonPlugin</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\library\Moon.GdYaml\Moon.GdYaml.fsproj" Condition="'$(Configuration)' == 'Debug'" />
        <ProjectReference Include="..\..\library\Godot.Editor\Godot.Editor.csproj" />
    </ItemGroup>
</Project>
